### ISSUE TITLE
Give this package the same version as the packages that it wraps

### ISSUE THREAD

**Issue by st3fan** [mozilla/rust-components-swift#10]
Is it possible to give this package the same version of the package that it wraps? As in, the latest release of this package would be `85.4.1` ?

cc @skhamis

**Comment by skhamis** [comment]
Hey @st3fan, awesome idea! We actually have that incoming soon (I realize we don't have issues in this repo due to JIRA syncing with a-s -- will also get that fixed) in @tarikeshaq PR for automated cut released https://github.com/mozilla/rust-components-swift/pull/8

- I was mainly waiting to bump the version numbers until we got all components in and switch to a slower release style (only bump when a-s bumps)

**Comment by mhammond** [comment]
Another vague consideration here is the concept of "cherry-picking" components we've been discussing in the context of android (cc @bendk) - eg, consider a hypothetical scenario where our major logins refactor has landed on app-services/main, but we want to make an iOS release that continues to use the older version.

(This remains hypothetical for now, but worth considering)

**Comment by st3fan** [comment]
I like cherry picking because Focus only needs Glean and Nimbus and none of the sync dependencies. I assume that would shrink the app size considerably?

**Comment by skhamis** [comment]
r-c-s now uses the same version as a-s so this is issue is resolved
